import { Component, OnInit } from '@angular/core';
import { CurrencyPipe } from '@angular/common';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styles: [],
  providers: [ CurrencyPipe ]
})
export class CalculatorComponent implements OnInit {

  monto:any
  producto:any
  bancos:Object

  constructor(private cur:CurrencyPipe) {
    this.bancos = {
      'Bancomer' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '18 msi' : {msi: 18, min: 1200, dif: 0, bon: [{ status: true, producto: {'all': { min: 25000, max: 2500,
          bon: (m) => {return (m/18) >= 2500 ? `1 mes de bonificación: $2,500` : `1 mes de bonificación: ${this.cur.transform(m/18,'MXN','symbol-narrow','.2-2')}`},
          bonTotal: (m) => { return this.cur.transform(m-(m/18),'MXN','symbol-narrow','.2-2')}
        }} }]},
        '21 msi' : {msi: 21, min: 20000, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '24 msi' : {msi: 24, min: 30000, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
      },
      'Banorte' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: true, producto: {'all': { min: 12000, max: 0,
          bon: (m) => { return '10% de bonificación directamente en el banco'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.1),'MXN','symbol-narrow','.2-2') } }} }]},
        '18 msi' : {msi: 18, min: 1200, dif: 0, bon: [{ status: true, producto: {'all': { min: 12000, max: 0,
          bon: (m) => { return '10% de bonificación directamente en el banco'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.1),'MXN','symbol-narrow','.2-2') } }} }]},
      },
      'HSBC' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2') } },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
        '18 msi' : {msi: 18, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
        '24 msi' : {msi: 24, min: 20000, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$400 de descuento con código HSBC400'},
          bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Paquete': { min: 10000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} },
                                                                    'Crucero': { min: 8000, max: null,
                                                                      bon: (m) => { return '$400 de descuento con código HSBC400'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-400,'MXN','symbol-narrow','.2-2')} }} }]},
      },
      'Scotiabank' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 4000, max: null,
          bon: (m) => { return '$250 de descuento con código SCOTIABANK250'},
          bonTotal: (m) => { return this.cur.transform(m-250,'MXN','symbol-narrow','.2-2') }  },
                                                                    'Paquete': { min: 8000, max: null,
                                                                      bon: (m) => { return '$250 de descuento con código SCOTIABANK250'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-250,'MXN','symbol-narrow','.2-2') }  },
                                                                    'Cruceros': { min: 6000, max: null,
                                                                      bon: (m) => { return '$250 de descuento con código SCOTIABANK250'},
                                                                      bonTotal: (m) => { return this.cur.transform(m-250,'MXN','symbol-narrow','.2-2') }  }} }]},
        '18 msi' : {msi: 18, min: 15000, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '24 msi' : {msi: 24, min: 20000, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
      },
      'Banamex' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '18 msi' : {msi: 18, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
      },
      'Santander' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
        '12 msi' : {msi: 12, min: 1200, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
        '15 msi' : {msi: 15, min: 15000, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
        '18 msi' : {msi: 18, min: 15000, dif: 0, bon: [{ status: true, producto: {'Hotel': { min: 2500, max: 0,
          bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
          bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Tour': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } },
                                                                              'Traslado': { min: 2500, max: 0,
                                                                                bon: (m) => { return '5% de descuento adicional con el código SANTANDERPT5'},
                                                                                bonTotal: (m) => { return this.cur.transform(m-(m*.05),'MXN','symbol-narrow','.2-2') } }} }]},
      },
      'Amex' : {
        '3 msi' : {msi: 3, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '6 msi' : {msi: 6, min: 1200, dif: 3, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]},
        '9 msi' : {msi: 9, min: 1200, dif: 0, bon: [{ status: false, producto: {'all': { min: 0, max: 0, bon: (m) => { return ''} }} }]}
      },
    }
  }

  ngOnInit() {
  }

  getMonto(){
    let result = this.monto ? parseFloat(this.monto.replace(/,/gm, '')) : 0
    return result
  }

}
